name: Build and Release new 
on: 
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  
  build:
    name: build partner apk
    permissions:
      contents: write
    runs-on: windows-latest

    steps:
      - name: Installing Checkout
        with: 
          ref: master

        uses: actions/checkout@v4
     
      - name: Setting up java
        uses:  actions/setup-java@v4.1.0
        with: 
          distribution: 'oracle'
          java-version: 17

      - name: Setting up Flutter
        uses: subosito/flutter-action@v2.13.0
        with:
          flutter-version: '3.19.6'
          channel: 'stable'
     
      

      - name: Get Package
        run: |
          echo "Working directory is now $(pwd)"
          flutter pub get 
        
     
      - name: Build APK
        run: flutter build apk --no-tree-shake-icons
        
     
      - name: Upload Artitfacts
        uses: actions/upload-artifact@v4.3.1
        
        with:
          name: Release Partner APK
          path: |
            build/app/outputs/flutter-apk/app-release.apk

      - name: Releasing build
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          tag: v1.0.${{github.run_number}} 
          commit: master
          body: |
            Release notes for v1.0.${{ github.run_number }}
